server:
  port: 8086

spring:
  application:
    name: notification-service
  data:
    redis:
      host: localhost
      port: 6379
      password: flowmail_redis
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.flowmail.*"
      auto-offset-reset: earliest

management:
  endpoints:
    web:
      exposure:
        include: health,info
